### ISSUE TITLE
all iframes are allowed

### ISSUE THREAD

**Issue by lovasoa** [npm/marky-markdown#108]
https://github.com/npm/marky-markdown/blob/b6e752bf799d427b19a792515710321b81299d12/lib/sanitize.js#L57-L59

The comment says that it allows only iframes from youtube. In fact, it allows iframes from anywhere, as long as the URL contains `//youtube.com`.

**Comment by revin** [comment]
Thanks, @lovasoa. I submitted a PR to fix this.

**Comment by revin** [comment]
PR updated per [suggestion](https://github.com/revin/marky-markdown/commit/e2de8314c3098fe675ebadf3d5407571b4a09da7#commitcomment-15435987) from @lovasoa, thanks for the help.
