### ISSUE TITLE
Markdown Rendering Issues on npmjs.com

### ISSUE THREAD

**Issue by jhuckaby** [npm/marky-markdown#126]
I have discovered a number of Markdown rendering bugs on npmjs.com, which I have compiled into a package with examples:

https://www.npmjs.com/package/npm-markdown-bugs

Compare this to the same exact Markdown syntax on GitHub, and you can see the issues:

https://github.com/jhuckaby/npm-markdown-bugs

I figured this would be better than entering 5 separate issues. But if you would prefer that, please let me know.

Thanks!

**Comment by ashleygwilliams** [comment]
thanks so much for filing :) and extra thanks for the great test module!

**Comment by revin** [comment]
"Incorrect Code Indents" and "Tabs Are Rendered Extremely Wide" might be candidates for marky fixes; essentially the problem there is that browsers are rendering `\t` characters with traditional eight-character width. Github is replacing them with four spaces. We should probably look around to determine under which circumstances they make this substitution (it could just be that tabs in leading whitespace get replaced) and follow suit.

"Incorrect Nested List Indents", "No Space After Lists", and "Tables Centered By Default" look to me like newww CSS issues, not markdown-to-HTML errors.

**Comment by jhuckaby** [comment]
Thanks @revin -- I'll resubmit "Incorrect Nested List Indents", "No Space After Lists", and "Tables Centered By Default" as CSS rendering issues in the https://github.com/npm/newww repo.

**Comment by ashleygwilliams** [comment]
thank you so much @jhuckaby ! i was about to do this. so awesome that you already have :)

**Comment by jhuckaby** [comment]
My pleasure @ashleygwilliams :+1:

**Comment by revin** [comment]
@jhuckaby ditto on the thanks, I really like the idea of having a markdown torture test module specifically there to look for rendering bugs. (And sorry to keep bouncing you around between issue trackers!)

**Comment by jhuckaby** [comment]
Haha, no problem @revin -- happy to help.  I'll continue to add test cases to my torture test module as I find them 😉

**Comment by revin** [comment]
The marky-specific parts of this were fixed in #127; closing
