### ISSUE TITLE
Suggestion: Document releases

### ISSUE THREAD

**Issue by zeke** [npm/marky-markdown#148]
It would be nice to be able to peruse release notes at https://github.com/npm/marky-markdown/releases to get a high-level view of what's changing.

I know @othiym23, @iarna, and @zkat have a process for documenting [npm releases](https://github.com/npm/npm/releases). Maybe they can provide some insight on how their release process works.

**Comment by ashleygwilliams** [comment]
hay-- i have been writing them in the CHANGELOG. happy to copy over.
