### ISSUE TITLE
Feature request: add support for task lists

### ISSUE THREAD

**Issue by amercier** [npm/marky-markdown#166]
Hi, I remarked [GitHub's Markdown task lists](https://github.com/blog/1825-task-lists-in-all-markdown-documents) are not properly rendering on https://www.npmjs.com/:

#### Expected

[![screen shot 2016-03-12 at 8 42 45 pm](https://cloud.githubusercontent.com/assets/1246795/13726958/188611ba-e893-11e5-9851-947e8406d566.png)](https://github.com/amercier/npm-package-skeleton)

Ex: https://github.com/amercier/npm-package-skeleton

#### Actual

[![screen shot 2016-03-12 at 8 45 40 pm](https://cloud.githubusercontent.com/assets/1246795/13726967/65e249d8-e893-11e5-9448-0efbc043a11f.png)
)](https://www.npmjs.com/package/package-skeleton)

Ex: https://www.npmjs.com/package/package-skeleton

It would be amazing if this feature was supported on npmjs.com! What do you guys think?

**Comment by revin** [comment]
Hi @amercier, thanks for the request! I didn't want to let this sit here without a response, but I'm not the one to make a final decision on it; @ashleygwilliams is my boss on this repo :smile:, so it's up to her in the end.

That said, I personally don't see there being a major problem with supporting this, but I am in the middle of overhauling the way we parse markdown lists in general, so I probably can't do it until after that's finished.

For my own future reference, the task is to perform the following rendering on list items:

| leading | renders |
|---|---|
|`[ ]` | `<input class="task-list-item-checkbox" disabled="" type="checkbox">` |
|`[x]` | `<input class="task-list-item-checkbox" checked="" disabled="" type="checkbox">` |

**Comment by revin** [comment]
fixed in #168.
