### ISSUE TITLE
Using & in the package discription results in it getting displayed incorrectly on the package main page.

### ISSUE THREAD

**Issue by rnjailamba** [npm/marky-markdown#167]
The issue is that package description is displayed correctly on the listing page[http://imgur.com/9a16Rh0] and on my profile page[http://imgur.com/lDveJYz] [https://www.npmjs.com/~rnjailamba12] however it is incorrect on the main page of the package[Photo of issue - http://imgur.com/xLfY5nc][Link -
https://www.npmjs.com/package/urlgenerator] so this seems like a small issue which can be fixed at your end.
Stephanie Snopek has told me that the issue is with marky-markdown[http://i.imgur.com/KjjLlvG.png] thats why im here :)

**Comment by revin** [comment]
Hi @rnjailamba, thanks for submitting! Marky's `parsePackageDescription(...)` function is returning `Simple url generation for Node JS , Express JS that works! [www.abc.xyz?def=ghi&amp;jkl=mno]` which, as you can see, has the `&` escaped as an HTML entity. I think we've run into this type of thing before where the npmjs.com site is escaping the description again, and it causes exactly the type of issue you're seeing; we'll have to work it out with the folks in charge of [npm/newww](https://github.com/npm/newww) to coordinate this and agree on who should be doing what :smile:

**Comment by revin** [comment]
Well looky here, the issue for that is still open: check out [npm/newww#1789](https://github.com/npm/newww/issues/1789). I'll close this one in favor of that, same as we did for #124. @rnjailamba does that sound OK to you?

**Comment by rnjailamba** [comment]
Sure @revin!!
Looking forward to your fix.

**Comment by rnjailamba** [comment]
@revin 
I checked out the npm js website [code](https://github.com/npm/newww/blob/6d9f1b3aa090ecc26bfd109a7f24dea5bad326c9/presenters/package.js)

**Comment by revin** [comment]
@rnjailamba I don't actually work on the npm web site at all, so I'm not all that familiar with the code in detail, but per the issue I linked you to, it's a matter of how they manage the Handlebars templates for these pages. There are certain types of data they need escaped, and certain types they don't, so the fix isn't necessarily trivial (as in, fixing this will break the cases the current code fixed (which broke this case among others)). The best thing I can suggest is to keep track of the newww issue; if they need us to change anything in marky here, we'll get right on it.
