### ISSUE TITLE
Does not work with HapiJS 8.1.0

### ISSUE THREAD

**Issue by Cecildt** [npm/marky-markdown#18]
When I try to include marky-markdown in my HapiJS project then the application does not start up anymore. If I remove the require to marky then the application starts as normal. 

Let me know what other info is needed.

**Comment by zeke** [comment]
Hey @Cecildt. Sorry I somehow missed this issue. Can you share the error message you're seeing?

**Comment by Cecildt** [comment]
Hey @zeke, I get no error. The web application just does not start. When I comment out the require statement to marky then the web application starts. I put the code on github: https://github.com/Cecildt/hapi-marky

Check the file under server/controllers/base.js

Hope this helps.

**Comment by bcronin** [comment]
Could this be a Windows-specific issue? For what it's worth, I'm seeing something similar / possibly the same from this code:

```js
var marky = require("marky-markdown");
console.log("Will this display?");
```

The console.log statement...

*  **Does** display on my Mac v0.12.1 install of node
* **Does not** display on my Windows v0.12.0 install of node
* **Does not** display on my Windows v0.10.21 install of node

If I comment out ``require("marky-markdown")`` (i.e. line 1), it displays on all three.

**Comment by zeke** [comment]
That could definitely be the case. I don't know the first thing about how to debug this. Maybe @othiym23,  npm's resident Windows expert, can give us a clue as to how to make it break with a useful error message...

**Comment by Cecildt** [comment]
Hey @zeke, I updated my test project to the latest version of marky-markdown package and now it works.

**Comment by zeke** [comment]
sweet!
