### ISSUE TITLE
variable leak: tabWidth

### ISSUE THREAD

**Issue by aredridel** [npm/marky-markdown#180]
When integrating marky 7, I ran into our test suite flagging this leaking into global scope:

`The following leaks were detected:tabWidth`

**Comment by aredridel** [comment]
Failing test case in #181

**Comment by revin** [comment]
oops, that's my fault: https://github.com/revin/markdown-it-expand-tabs/blob/master/index.js#L5-L9 ; I'll fix it ASAP

**Comment by revin** [comment]
(Where's the 'dependency author is a n00b' label?)

**Comment by aredridel** [comment]
(Nowhere 'cause we all do this. It's one of the sharp corners of JS)

**Comment by revin** [comment]
ok I pushed [markdown-it-expand-tabs@1.0.10](https://www.npmjs.com/package/markdown-it-expand-tabs); we semver it in as `^1.0.7` so it should work OOTB now, no?

**Comment by revin** [comment]
Got a new PR: #186.

**Comment by revin** [comment]
Fixed by markdown-it-expand-tabs@1.0.10, test implemented here in #186
