### ISSUE TITLE
strange whitespace encoding causes epic id attribute fail

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#194]
https://github.com/ashleygwilliams/marky-test

steps to repro:
1. `git clone`
2. `npm install`
3. `npm test`
4. `open README.html`

<img width="1123" alt="screen shot 2016-05-31 at 7 12 34 pm" src="https://cloud.githubusercontent.com/assets/1163554/15693607/8bf8a3c8-2764-11e6-8771-da7c39e7d6f2.png">
<img width="540" alt="screen shot 2016-05-31 at 7 19 16 pm" src="https://cloud.githubusercontent.com/assets/1163554/15693616/99e9b3e6-2764-11e6-843b-d1d64753630a.png">

**Comment by revin** [comment]
😳 Fascinating!

`markdown-it` is _supposed_ to [normalize line endings](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/normalize.js), so this must be somehow making it through that; I'll start looking there for answers.

**Comment by revin** [comment]
ok, it's because the [regular expression markdown-it uses](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/normalize.js#L6) is skipping the `\r`line endings in this file.

@ashleygwilliams do you think that counts as a bug in `markdown-it`?

This is kind of a kick; according to [Wikipedia's _Newline_ article](https://en.wikipedia.org/wiki/Newline), `\r` by itself as a line ending was used on such systems as:

> Commodore 8-bit machines, Acorn BBC, ZX Spectrum, TRS-80, Apple II family, Oberon, Mac OS up to version 9, MIT Lisp Machine and OS-9

... so I have a (presumptuous) hunch that if I open a bug, it'll be written off as input error 😛 . I'm willing to give it a shot though.

But still, how cool would it be if people were authoring node packages on one of those platforms?

**Comment by revin** [comment]
(as the WP article points out, \r is a [valid line terminator in the Unicode standard](http://www.unicode.org/reports/tr14/tr14-32.html))

**Comment by ashleygwilliams** [comment]
@revin yeah that *def* sounds like a markdown it bug to me... but since you filed last time- do you want me to file?

also i love this bug

**Comment by revin** [comment]
If you totally want to or whatever, go for it; I don't mind doing it
tomorrow myself either though. Whoever has time first.

Agreed, this is a pretty great bug.

On Tuesday, May 31, 2016, ashley williams <notifications@github.com> wrote:

> @revin <https://github.com/revin> yeah that *def* sounds like a markdown
> it bug to me... but since you filed last time- do you want me to file?
>
> also i love this bug
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/npm/marky-markdown/issues/194#issuecomment-222865202>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAFygsZsSNL5hnpwHG7nj7SEhH4zuwZGks5qHNo4gaJpZM4IrDJN>
> .
>


-- 
--
Revin Guillen
rg@sevenite.com

**Comment by revin** [comment]
@ashleygwilliams [markdown-it#252](https://github.com/markdown-it/markdown-it/issues/252)

**Comment by revin** [comment]
ok they [fixed it](https://github.com/markdown-it/markdown-it/commit/6dbe532460ca519cd05c07a862555c90dfbe906a); presumably it'll be in markdown-it@6.0.5; which means we'll be blocked here until we merge #153 since we're still on 5.x in marky@7.

**Comment by revin** [comment]
Fixed in 8.0.

🍾 pour one out for a really great bug
