### ISSUE TITLE
Headers wrapped in links even if it already contains them.

### ISSUE THREAD

**Issue by jdalton** [npm/marky-markdown#200]
The change at https://github.com/npm/marky-markdown/commit/569d0256b517f2135c03a3d1a7abe939b1ceef24 introduced an issue where headers with links may still be wrapped if they were html links. See https://github.com/npm/marky-markdown/commit/569d0256b517f2135c03a3d1a7abe939b1ceef24#commitcomment-18103230.

**Comment by revin** [comment]
Nice find, thanks, I'll take a look. :+1:

**Comment by jdalton** [comment]
\cc @zackhall

**Comment by revin** [comment]
@jdalton seems I can replicate this with markdown like:

```
# <a href='foo'>Link</a> heading text
```

i.e., a markdown heading with HTML inside. Is that the kind of input you're talking about? Or is there another example? Just trying to make sure I understand the full scope of the input to expect. Thanks!

**Comment by jdalton** [comment]
Yep!
