### ISSUE TITLE
new improved README, move docs to wiki

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#213]
to help people understand what marky is trying to do, i'd like to rework the readme and move much of the information to the wiki as docs. thoughts @revin?

**Comment by zeke** [comment]
I would be in favor of a `docs` directory inside the repo itself. That way the docs are more accessible to users and still in version control.

GitHub wikis are not given much love as a product. You can git clone them, but you can't access wiki content via the GitHub API.

**Comment by revin** [comment]
... hmm ... my first reaction is to agree with @zeke about `docs/` over a GH wiki, but that's not a particularly strong opinion at all. @ashleygwilliams you're definitely more of a docs/teaching expert than I am, by far, so I defer to you.
