### ISSUE TITLE
ignore test files when publishing to npm?

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#222]
this occurred to me since i'm going to build a little landing page for marky. shall we ignore the tests on publish? thoughts @revin ?

**Comment by revin** [comment]
I'd be in favor of it. If someone wants to run the tests, they can just clone the repo. You need the whole thing [including `devDependencies` ](https://github.com/npm/marky-markdown/blob/master/test/fixtures.js#L20) for the tests to be complete, so I see no problem with requiring folks to have the full environment.
