### ISSUE TITLE
Linking to headers that contain links

### ISSUE THREAD

**Issue by nwhetsell** [npm/marky-markdown#224]
Is it possible, on npm, to link to a header that itself contains a link? For example,

```markdown
## Examples
```

lets you use `#examples` as part of a URL. On the other hand,

```markdown
## [Examples](https://github.com/nwhetsell/csound-api/tree/master/examples)
```

doesn’t let you use `#examples` as part of a URL on npm; https://www.npmjs.com/package/csound-api#examples doesn’t go to the Examples section of csound-api on npm, but https://github.com/nwhetsell/csound-api#examples does on GitHub.

Here’s a short script showing what marky-markdown produces in these cases:

```javascript
const marky = require('marky-markdown');

let HTML = marky('## Examples').html();
console.log(`==> ${HTML}`);
// ==> <h2 id="user-content-examples" class="deep-link"><a href="#examples">Examples</a></h2>

HTML = marky('## [Examples](https://github.com/nwhetsell/csound-api/tree/master/examples)').html();
console.log(`==> ${HTML}`);
// ==> <h2><a href="https://github.com/nwhetsell/csound-api/tree/master/examples">Examples</a></h2>
```

**Comment by ashleygwilliams** [comment]
hey! thanks for filing this. we are striving towards GitHub partity, so this is very helpful. are you interested in contributing? we'd welcome a PR! otherwise, we'll look into it as soon as we can. this is the plugin we use to generate the anchor for the headings, it seems it is just not catching the link content! https://github.com/Flet/github-slugger

**Comment by nwhetsell** [comment]
Sure, I’ll take a crack at it when I have a sec.

**Comment by wooorm** [comment]
I created a PR for this a while back: GH-38; it most definitely cannot be merged now though, but it might be useful as inspiration and places where to look!

I can’t remember much from it, but from the description I wrote back then it also required changes to the CSS of the site 😬

**Comment by nwhetsell** [comment]
@wooorm Awesome, thanks!

**Comment by ashleygwilliams** [comment]
d'aww sorry that the site held us up during thatPR @wooorm. i def don't require that anymore (totally decoupled from the npm site, they just happen to use us a bunch.) i might actually try to resurrect that PR...

**Comment by wooorm** [comment]
Cool! 👍

Well the code for the PR is pretty minimal so that should be not too hard to resurrect, but I’m guessing the style has changed a bit since then? (P.S. The style is in the new private www I think?)

**Comment by ashleygwilliams** [comment]
yeah, i can explain the required styling changes to the team :)

**Comment by wooorm** [comment]
Haha great 👌 Anything I can still help with?

**Comment by ashleygwilliams** [comment]
will probably ping you with the resurrected PR for a review, if you're up for it? @wooorm

**Comment by wooorm** [comment]
Deal!

**Comment by revin** [comment]
> Well the code for the PR is pretty minimal so that should be not too hard to resurrect, but I’m guessing the style has changed a bit since then?

I rewrote this part as a markdown-it plugin a while back rather than using the parsed cheerio DOM 😕, so the code will have to be different now, sorry about that.

**Comment by revin** [comment]
If you don't want to deal with learning the markdown-it internal stuff for this, I can take it on. Just let me know.
