### ISSUE TITLE
Make anchor links work by default

### ISSUE THREAD

**Issue by kasbah** [npm/marky-markdown#231]
By default `options.prefixHeadingIds` is set to `true` and thus heading ids are prefixed with `user-content-` which makes the anchor links not work by default. If you set `prefixHeadingIds` to `false` the anchor links will work as they are, no javascript required on the page. 

An alternative could be to prefix the hrefs in the anchor links too and open up an option for it. 

P.S. Have to congratulate you on very readable source code, the documentation isn't complete but I can just dive in and find out what the options actually do.

**Comment by kasbah** [comment]
Another way to make them work by default I believe would be to use a `name` attribute like `<h1 id="user-content-the-anchor" name="the-anchor">` but I haven't been able to confirm this as the `name` attribute is disappearing (the test fails): https://github.com/kasbah/marky-markdown/commit/2e73033294987b5ea845aec567ef66c57fd8ceaf

**Comment by revin** [comment]
Oh cool, yeah this might be something we could support. In general the goal is to render as close to what github does as we can, by default; but that doesn't mean we can't support other good use cases via options.

One thing that I tend to forget is that a modification like you have in your commit also requires getting the `name` attribute in the sanitize.js module; that's almost surely what's stripping it out.

**Comment by kasbah** [comment]
Thanks, that sorted it, turns out `name` attributes are only supported on `<a>` tags though so I put it there with #232.

**Comment by revin** [comment]
Closing for now; discussion in #232
