### ISSUE TITLE
# with space preceding interpreted as heading

### ISSUE THREAD

**Issue by kasbah** [npm/marky-markdown#233]
I was considering filing this with markdown-it but I haven't dove into how much customization marky does and since marky's goal is GitHub parity I am asking here first. 

In this [readme rendered by marky](http://render-readmes.preview.kitnic.it/boards/github.com/8BitMixtape/NextLevelEdition/#8bit-mixtape-nextlevel-shit) the linked title shouldn't be a title. [Here it is rendered on Github](https://github.com/8BitMixtape/NextLevelEdition#how-to-install). 

There is a space preceding the `#` so it seems GitHub doesn't consider it a title but marky does.

**Comment by revin** [comment]
markdown-it.github.io is useful in these cases, and it looks like markdown-it is treating it as a header in its own; it's not something we're customizing.

As you'll find, markdown-it takes CommonMark compliance very seriously, and GitHub ... doesn't. This looks like another case of GH deviating from CM, so I'd say we should keep this issue around and try to match GH behavior. What do you think @ashleygwilliams?

**Comment by ashleygwilliams** [comment]
yeah, GitHub is the gold standard, so if GitHub does it, we should. 😅 

thanks for all these helpful issues @kasbah !! are you interested in contributing? this is a great starter issue, and i'd (and also probably @revin) would be happy to pair with you.

**Comment by revin** [comment]
Won't know for sure until I dig in, but I'm guessing this requires a markdown-it plugin that replaces/augments the [stock heading parsing rule](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_block/heading.js), or something near that.
