### ISSUE TITLE
Remove `pretty` from dependencies and do not prettify in CLI

### ISSUE THREAD

**Issue by eush77** [npm/marky-markdown#24]
1. The only file that uses `pretty` is the CLI. The main stuff does not depend on it.
1. It wraps the resulting HTML unconditionally, which means that the user can't opt out. So the CLI is rather a CLI for `marky-markdown` + `pretty` rather than for `marky-markdown` alone (which it should be).
1. Prettifying can break things, because HTML is so space-sensitive. And it does (code blocks for example).
1. It's not very unixy: if the user really wanted to prettify the output, she would pipe it to the CLI version of `pretty` or any other program. Combining programs in this way is more configurable and robust.

**Comment by zeke** [comment]
Point taken. I will accept a patch for this.
