### ISSUE TITLE
end support for 0.10, 0.12, and iojs

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#240]
if we update to `standard@8.0.0` #239 we will lose support for 0.10, 0.12, and iojs. (https://github.com/npm/marky-markdown/blob/master/.travis.yml#L7-L9)

thoughts on this? is standard worth it? should we still be supporting node versions that are EOL? ping @revin

**Comment by revin** [comment]
From https://github.com/nodejs/LTS#lts_schedule it would seem that if we _really_ wanted to make the case for supporting 0.10 & 0.12, we could, but only until October and December, respectively. Personally I would be surprised if we had users 1) on those platforms, 2) developing marky or running `npm test` on marky, and 3) really wanting our new features. 

I'd be OK with dropping support, but I'm also fine waiting until the EOL versions are really truly EOL too, like I'm not totally convinced a code style checker is critical enough that we can't wait a few months. On the other hand, it's just a `devDependency` anyway, right? People can still _use_ marky wherever. That makes it easier for me to accept.

**Comment by ashleygwilliams** [comment]
yeah i think i agree with you. let's move forward with standard 8.0 and losing node 0.10 and 0.12 dev support
