### ISSUE TITLE
Keep align property

### ISSUE THREAD

**Issue by kasbah** [npm/marky-markdown#241]
It seems the `<p>` `align` property is respected on GitHub but not by marky. 

Compare these and notice the image centering:

https://github.com/kanflo/aaduino/

http://add-aaduino.preview.kitnic.it/boards/github.com/kitnic/aaduino/

The relevant code is:
```html
<p align="center">
  <img src="https://raw.githubusercontent.com/kanflo/aaduino/master/aaduino.jpg" alt="The AAduino"/>
</p>
```
In the marky version the `align` is stripped out. It should probably be added to the allowed properties of `<p>` in the sanitizer.

**Comment by revin** [comment]
Good find, @kasbah, thanks! Submitted a PR for the next release.
