### ISSUE TITLE
single backslash in an inline code block inside table parsed differently than GitHub MD

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#252]
from https://github.com/npm/www/issues/31 via @poiuiopoiu 

NPM appears to use a parser that follows the common mark spec and it differs from github in a few ways.  My issue is writing a single backslash in an inline code block.

The Github way is 

```
`\`
```

But that trips up the NPM parser, since common mark treats that as an escaped backtick.  The right way to do it for NPM is

```
`\\`
```

But that messes up github, which interprets it as 2 backslashes.

I'd guess that most modules use the github markdown style, so I guess I would consider this a npm website bug

**Comment by revin** [comment]
Is it possible this is the web site's template processing or something like that?

I just ran
```markdown
some test `\` text
```
through marky via CLI, and got back
```html
<p>some test <code>\</code> text</p>
```

Both versions have the single slash as expected.

**Comment by ashleygwilliams** [comment]
oh HUH. thoughts @jefflembeck @aredridel ?

**Comment by ashleygwilliams** [comment]
actually closing this in favor of the www issue.

yay issue shuffling. thanks for the quick feedback @revin

**Comment by ashleygwilliams** [comment]
actually-- @revin did you run with 8 or current? looks like the website uses 8.0.0 https://github.com/npm/npm-website/blob/master/package.json#L133

i don't think we did anything that should affect this and i've seen escaping issues with the website templating before but it might be worth checking just in case?

**Comment by revin** [comment]
oh, good call @ashleygwilliams I did it with current master. I just ran it again at the v8.0.0 tag and got the same (correct) results. That's using `markdown-it@7.0.1` internally, fwiw.

**Comment by ashleygwilliams** [comment]
from https://github.com/npm/www/issues/31
-------
@aredridel thank you for replying!  I set up a dummy package `badness-10000` to demonstrate:

```
# badness 10000

| a | b | c | d | e | f |
|---|:-:|---|:-:|---|:-:|
| `a` | b | `c` | d | `` ` `` | |
| `e` | f | `g` | h | `|` | |
| `\` |   | `]` |   | `[` | |
```

github: https://gist.github.com/poiuiopoiu/fa85d4166a273ec7692d227028336ac5

<img width="264" alt="screen shot 2016-10-30 at 12 12 21" src="https://cloud.githubusercontent.com/assets/22307420/19839151/2b08621c-9e9a-11e6-90d5-7d107d5e9e0f.png">

NPM: https://www.npmjs.com/package/badness-10000

<img width="607" alt="screen shot 2016-10-30 at 12 11 52" src="https://cloud.githubusercontent.com/assets/22307420/19839144/2706f44e-9e9a-11e6-8962-429144912e7e.png">

Please feel free to completely remove all versions of the package -- I have no plans to use the name.

**Comment by revin** [comment]
This is interesting; does GitHub escape _any_ characters in inline code blocks? TIL you can delimit your code blocks (both inside and outside tables) with as many backticks as you like, as long as you have the same amount on both ends of the code block.

Reason I ask is, would it be possible to just modify the table parsing rule (and maybe the code rule) such that it disables backslash escaping altogether?

**Comment by revin** [comment]
reference for my TIL above: https://github.com/github/markup/issues/363
