### ISSUE TITLE
`lodash.assign` is deprecated, makes all the DependencyCI tests break

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#254]
let's record why this is happening and how to fix it, even if we ultimately don't plan on fixing it right this second (potentially because we are going to continue to support older versions of Node).

**Comment by jdalton** [comment]
I dropped the deprecation message for now. May add it back once 0.12 is officially dropped Jan. There's plenty of deprecation/warnings when installing npm packages. Is it a bug that it causes test fails?

**Comment by zeke** [comment]
If the plan for `marky-markdown` is to continue supporting node@'<4', Switching to http://ghub.io/object-assign would do the trick. Otherwise, the dependency can be dropped in favor of `Object.assign()`

**Comment by jdalton** [comment]
If and when I add the deprecation message back it'll be on a major bump so shouldn't effect marky-markdown.

**Comment by ashleygwilliams** [comment]
thanks so much @jdalton! we want to deprecate when 0.12 is officially dropped as well so it sounds like we are totally in sync. thanks for reaching out too :) super appreciated
