### ISSUE TITLE
gitignore `dist.js`, still publish to registry

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#262]
merge conflicts in this built file are a huge PITA. we shoudn't be commiting it anyways. let's fix this for 9.0.

**Comment by karanjthakkar** [comment]
@ashleygwilliams So if I'm understanding you correctly, you want the `dist` folder in `.gitignore` but you also want it to be published to npm?

**Comment by ashleygwilliams** [comment]
correct @karanjthakkar! this page of npm docs should be helpful :) https://docs.npmjs.com/files/package.json#files

lemme know if you want help!
