### ISSUE TITLE
badge rendering in description field due to truncated line?

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#267]
from https://github.com/npm/www/issues/49

might be related to https://github.com/npm/marky-markdown/issues/195

the generate code is in the `description` field
```html
<p class="package-description"><a href="http://travis-ci.org/socketio/socket.io-client"><img src="https://secure.travis-ci.org/socketio/socket.io-client.svg?branch=master"></a> [<img src="https://david-dm.org/socketio/socket.io-client.svg">](https://david-dm.org/socketio/socket.io-</p>
```

source code:

```
[![Build Status](https://secure.travis-ci.org/socketio/socket.io-client.svg?branch=master)](http://travis-ci.org/socketio/socket.io-client)
[![Dependency Status](https://david-dm.org/socketio/socket.io-client.svg)](https://david-dm.org/socketio/socket.io-client)
[![devDependency Status](https://david-dm.org/socketio/socket.io-client/dev-status.svg)](https://david-dm.org/socketio/socket.io-client#info=devDependencies)
![NPM version](https://badge.fury.io/js/socket.io-client.svg)
![Downloads](http://img.shields.io/npm/dm/socket.io-client.svg?style=flat)
[![](http://slack.socket.io/badge.svg?)](http://slack.socket.io)
```

github generated code
```
<p><a href="http://travis-ci.org/socketio/socket.io-client"><img src="https://camo.githubusercontent.com/45c517488b89c24db4d05ffa20919bdd705f4307/68747470733a2f2f7365637572652e7472617669732d63692e6f72672f736f636b6574696f2f736f636b65742e696f2d636c69656e742e7376673f6272616e63683d6d6173746572" alt="Build Status" data-canonical-src="https://secure.travis-ci.org/socketio/socket.io-client.svg?branch=master" style="max-width:100%;"></a>
<a href="https://david-dm.org/socketio/socket.io-client"><img src="https://camo.githubusercontent.com/cd370ec853566316a5cdacf1227a8acf86f4b227/68747470733a2f2f64617669642d646d2e6f72672f736f636b6574696f2f736f636b65742e696f2d636c69656e742e737667" alt="Dependency Status" data-canonical-src="https://david-dm.org/socketio/socket.io-client.svg" style="max-width:100%;"></a>
<a href="https://david-dm.org/socketio/socket.io-client#info=devDependencies"><img src="https://camo.githubusercontent.com/409c34f01c2b2ec38b8e49a56d80be2f3ab13b7b/68747470733a2f2f64617669642d646d2e6f72672f736f636b6574696f2f736f636b65742e696f2d636c69656e742f6465762d7374617475732e737667" alt="devDependency Status" data-canonical-src="https://david-dm.org/socketio/socket.io-client/dev-status.svg" style="max-width:100%;"></a>
<a href="https://camo.githubusercontent.com/af44b4592d3a6a701aa406bf39c7f62903c60544/68747470733a2f2f62616467652e667572792e696f2f6a732f736f636b65742e696f2d636c69656e742e737667" target="_blank"><img src="https://camo.githubusercontent.com/af44b4592d3a6a701aa406bf39c7f62903c60544/68747470733a2f2f62616467652e667572792e696f2f6a732f736f636b65742e696f2d636c69656e742e737667" alt="NPM version" data-canonical-src="https://badge.fury.io/js/socket.io-client.svg" style="max-width:100%;"></a>
<a href="https://camo.githubusercontent.com/aba322fe396e0fe2bf47e178c9bfc8db6a83ffaf/687474703a2f2f696d672e736869656c64732e696f2f6e706d2f646d2f736f636b65742e696f2d636c69656e742e7376673f7374796c653d666c6174" target="_blank"><img src="https://camo.githubusercontent.com/aba322fe396e0fe2bf47e178c9bfc8db6a83ffaf/687474703a2f2f696d672e736869656c64732e696f2f6e706d2f646d2f736f636b65742e696f2d636c69656e742e7376673f7374796c653d666c6174" alt="Downloads" data-canonical-src="http://img.shields.io/npm/dm/socket.io-client.svg?style=flat" style="max-width:100%;"></a>
<a href="http://slack.socket.io"><img src="https://camo.githubusercontent.com/74a344c126481fb80da4357a0251a0c868b9b528/687474703a2f2f736c61636b2e736f636b65742e696f2f62616467652e7376673f" alt="" data-canonical-src="http://slack.socket.io/badge.svg?" style="max-width:100%;"></a></p>
```

**Comment by revin** [comment]
Very interesting. The markdown above renders fine in marky 7 (that's what's on the site, correct?) if I put the whole thing in a string, so I suspect this is somehow usage related rather than being internal to the parser.

**Is the npm web site by chance slicing the first 255 characters out of this paragraph and sending that to marky?**

IIRC an older version in `newww` generated that part of the project pages by passing a markdown snippet to our `parsePackageDescription(...)` method; the snippet was basically the package.json `description` field, or the first paragraph after the main heading as a fallback. Since the `socket.io-client` package lacks a `description`, ... is that what's happening here? It sure feels like a 255-character truncation, judging by the rendered result.

@ashleygwilliams can you please look at that when you have an opportunity?

**Comment by ashleygwilliams** [comment]
hrrrrrm. it may still be that you are right @revin, but #268 seems to suggest that something funky is happening with links and truncation. i'll take a look at the www repo now to see if the website is doing anything. though given that #268 is not in the description field, i'm more likely to believe it has something to do with how we are parsing links.

**Comment by aredridel** [comment]
It's definitely truncated: in www, we've got `<a href="http://travis-ci.org/socketio/socket.io-client"><img src="https://secure.travis-ci.org/socketio/socket.io-client.svg" /></a> <a href="https://david-dm.org/socketio/socket.io-client"><img src="https://david-dm.org/socketio/socket.io-client.svg" /></a> [![dev` in the package description field. It's totally our bad, getting bad data from the registry.

**Comment by ashleygwilliams** [comment]
fascinating, @aredridel ~ have you checked out #268 ? is it related?

**Comment by aredridel** [comment]
Oh dear. Um, yes, I fully expect that to be related. 64k is a shall we say 'smoking gun' number.

**Comment by ashleygwilliams** [comment]
🚬  🔫

**Comment by aredridel** [comment]
Yeah. This is our internal registry-relational disservice causing this, both cases.

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/registry/issues/68
