### ISSUE TITLE
README content missing or truncated

### ISSUE THREAD

**Issue by eXigentCoder** [npm/marky-markdown#268]
This might be related to [#267](https://github.com/npm/marky-markdown/issues/267) but I'm not sure.

My full README renders correctly [here on GitHub](https://github.com/eXigentCoder/swagger-spec-express#addresponseheader) however the content is [truncated/missing on npm](https://www.npmjs.com/package/swagger-spec-express#addresponseheader).

If I had messed up the formatting, I would expect it to at least show up on npm after that point, but maybe in an unexpected way but for the content to be completely missing, I think it could be a bug.

**Comment by revin** [comment]
Looks like it truncates right at the 64kb boundary of the original markdown.

From the command line, marky 7 can process the whole thing just fine from a file; @ashleygwilliams is there anything in the npm web site code that might impose a 64kb limit?

**Comment by ashleygwilliams** [comment]
🤔 i will investigate, @revin!

**Comment by eXigentCoder** [comment]
Thanks, thought I might be going crazy for a while there!

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/registry/issues/68
