### ISSUE TITLE
support align attributes on images in markdown readme files

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#269]
from https://github.com/npm/www/issues/51 by @revelt 

<hr>
Hi all,
You probably noticed that GitHub let's you float images on the README markup documents using `align="left|right"`, but npmjs.com does not. This is counter-intuitive since GitHub doesn't have the sidebar on the right, but npmjs.com does — readme's are even more cramped on this website! Supporting the `align=` attribute on `<img>` tags would relieve this problem.
cheers,
Roy

**Comment by revin** [comment]
Similar to #241 only that was strictly for `<p>` elements

**Comment by marinintim** [comment]
Hi, I'll try to do it in the same way as #241.

**Comment by revin** [comment]
oh whoops sorry @marinintim I just did it since I had a couple of minutes to kill before a meeting 😞

**Comment by marinintim** [comment]
@revin, oh, ok :)
