### ISSUE TITLE
Pre tags' whitespace doesn't seem to be at the same width as on Github

### ISSUE THREAD

**Issue by lewiscowper** [npm/marky-markdown#284]
There's a noticeable difference in rendering between how marky-markdown and github renders whitespace in `<pre>` tags.

![screen shot 2016-11-03 at 23 00 36](https://cloud.githubusercontent.com/assets/593574/19987034/62d9852c-a219-11e6-9127-510515cd0256.png)

vs:

![screen shot 2016-11-03 at 23 01 06](https://cloud.githubusercontent.com/assets/593574/19987063/8682ec16-a219-11e6-80b3-609021badaf9.png)

If I can get `marky-compare` fixed then I can easily attach a diff to this issue.

**Comment by ashleygwilliams** [comment]
here's the diff from [`marky-compare`](https://github.com/npm/marky-compare): https://gist.github.com/ashleygwilliams/9b5342a282357d4fc59c12c60d30a51c

**Comment by revin** [comment]
Is there any chance this is the font choice on npmjs.com? In Brave on my mac, it renders as expected on npmjs.com/package/boxen, but on Chrome it appears as in your first screenshot; however, if I set, e.g., `font-family: 'courier new'` in Dev Tools, everything lines up. The Sources tab seems to indicate that each line is 15 characters long in the generated markup.

**Comment by ashleygwilliams** [comment]
oh interesting @revin - seems like we should refile this on [npm/www](https://github.com/npm/www)?

**Comment by revin** [comment]
@ashleygwilliams sure looks like it to me, yes.

**Comment by ashleygwilliams** [comment]
closed in favor of https://github.com/npm/www/issues/59
