### ISSUE TITLE
what is the difference between `test/headings` and `test/html-headings`

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#301]
it's not clear to me and i def wrote some redundant tests in my recent PRs, afaik

thoughts? i'd like to see this clarified or combined into a singular test file

**Comment by ashleygwilliams** [comment]
cc @revin (forgive me if you explained when u split the tests and i am forgetting)

**Comment by revin** [comment]
Hey @ashleygwilliams I believe that one was created in #278 as basically a clone of our existing heading tests, only for HTML heading tags rather than `#`-prefixed markdown headings. We could totally combine them if you wanted.

**Comment by ashleygwilliams** [comment]
got it. what's your thought? should they be in the same or different places? given #304 maybe we'll have a pattern of dealing with inline html and the html prefix works for that? are there other instances of where we deal with inline html? do we combine those or have different files?

**Comment by revin** [comment]
I could go either way on it, but I think if I had to pick one way I'd combine them into a single logical test group (perhaps in their own `describe(…)` sub-groups). For the most part, they're testing the same logical operation, just from two different parsing paths. So the test fixtures will often be separate but in the end the "thing" being tested is the same.

**Comment by revin** [comment]
oh also to answer your last question, there's kinda sorta one other place where we deal with `html_inline` specifically: the youtube `<div>` wrapper thing. But the other rule that goes with it is for `html_block` tokens, so there's not a huge difference there. We keep the tests around them together though.
