### ISSUE TITLE
Marky does not render a `code` tag and potentially adds extraneous divs when rendering a code block

### ISSUE THREAD

**Issue by samphippen** [npm/marky-markdown#318]
Using the repo [samphippen-marky-test](https://github.com/samphippen/samphippen-marky-test) as a testbed, I have a [simple readme](https://raw.githubusercontent.com/samphippen/samphippen-marky-test/master/readme.md) which just renders a single code block with the word foo in it. Here's the diff from [marky-compare](https://github.com/npm/marky-compare):

```diff
(master)$ ./index.js --package samphippen-marky-test && cat diff.diff
===================================================================
--- ./github_markup.html	github
+++ ./npm_markup.html	npm
@@ -1,NaN +1,NaN @@
-< pre > < code > foo <
-  /code></pre >
+< div class = "highlight" > < pre class = "editor editor-colors" > < div class = "line" > < span class = "text" > < span > foo < /span></span > < /div></pre > < /div>
```

Should the missing `code` tag be rendered?

Should the extra `<div class="line">`, `<span class="text">` and `<span>` tags be stripped here?

**Comment by ashleygwilliams** [comment]
given that github markup is the goal, yes, those should be stripped.

**Comment by ashleygwilliams** [comment]
this is related to https://github.com/npm/marky-markdown/pull/100, which is a long winded tale of breaking changes from markdown-it and how they relate to our syntax highlighter. @revin do you have thoughts on this? i feel like you definitely do.

**Comment by ashleygwilliams** [comment]
sam- the relevant code is here: https://github.com/npm/marky-markdown/blob/master/lib/plugin/code-wrap.js

**Comment by revin** [comment]
> @revin do you have thoughts on this? i feel like you definitely do.

😛  Oof, syntax highlighting. Yeah, this has been an area of no little pain in the past, and I've always been afraid of the day when we're running low on github-rendering-compatibility issues and it comes back to this, lol

Given that our goal is to be as close to what github renders as possible, I'd guess we have more problems than just the wrapping element(s). Until we're basically using the same highlighting library as github, it's always going to be at least somewhat different (I mean, I _assume_ it's a different library, but maybe not; I've never looked into that part). Even markdown-it stays out of it; you just bring your own highlighter to the party.

So from where I stand the question is less, "is this wrong?" and more "how much of this wrongness do we want to bite off?" ✨💃 ✨

**Comment by revin** [comment]
btw running marky with `{highlightSyntax: false}` renders this particular code block the same way github does. Perhaps we need to look at being more granular with the application of syntax highlighting rather than just running for all or none of the code blocks in a document.
