### ISSUE TITLE
README on npm doesn't match corresponding github tag (v9.0.1)

### ISSUE THREAD

**Issue by cspotcode** [npm/marky-markdown#319]
The readme on npm is outdated and doesn't match the readme for that exact version tag on github.

[On npm](https://www.npmjs.com/package/marky-markdown#cheerio-middleware) the readme says marky-markdown returns a cheerio object and you must call `.html()` to get a string of rendered HTML.

[On GitHub](https://github.com/npm/marky-markdown/blob/v9.0.1/README.md) that section is missing and the readme correctly states that marky-markdown returns a string, not a cheerio object.

**Comment by revin** [comment]
Interesting, @cspotcode, thanks for pointing it out. 9.0.0 was where we switched away from exporting a cheerio object, and if you install marky via `npm install`, the README in both 9.0.0 and 9.0.1 is the correct one, so I guess the site is displaying the one from 8.x or earler?

@ashleygwilliams is that a bug on the npm site or something?

**Comment by ashleygwilliams** [comment]
hey! this is def a bug on npm's side. if you use dist-tags to do pre-releases, the website doesn't update the readme. i'm on their case about it ;)

**Comment by ashleygwilliams** [comment]
this is fixed!!
