### ISSUE TITLE
Allow whitespace inside links and images

### ISSUE THREAD

**Issue by Andrews54757** [npm/marky-markdown#328]
Hello, I noticed that some shields from http://shields.io/ do not work. It displays like this: 

<img width="1265" alt="screen shot 2017-01-15 at 2 17 25 pm" src="https://cloud.githubusercontent.com/assets/13282284/21965414/608338f2-db2d-11e6-8d91-3ab1ea136207.png">

I have tried multiple things, such as editing spacing, but it doesn't work. The shields display correctly on Github. Also, I looked at other issues, which said it was because the description was truncated, but I do not think this was truncated.

Thank you.
Andrew

**Comment by revin** [comment]
Hi @Andrews54757, thanks for the report! Looks to me like it's the whitespace. The current readme has:
```markdown
[![NPM] (https://img.shields.io/badge/Module-Npm-blue.svg)] (https://www.npmjs.com/package/styleme)
[![Donate] (https://img.shields.io/badge/Donate-Paypal-brightgreen.svg)] (https://paypal.me/andrews54757)
```
and if I take out all whitespace between the brackets and parentheses, like so:
```markdown
[![NPM](https://img.shields.io/badge/Module-Npm-blue.svg)](https://www.npmjs.com/package/styleme)
[![Donate](https://img.shields.io/badge/Donate-Paypal-brightgreen.svg)](https://paypal.me/andrews54757)
```
the badges render. So you might try that in the meantime as a stop-gap solution. However, either way this is a GitHub compatibility thing for us here, so we'll have to fix it. Thanks for letting us know! 👍

**Comment by Andrews54757** [comment]
@revin Thank you

**Comment by revin** [comment]
Looks like this also affects normal link parsing. `[title] (destination)` (with a space in between the `]` and `(`) renders as a link on github but not via marky.

**Comment by revin** [comment]
Hmm. This is going to make it difficult to distinguish
```
some text with a [link with a space after the closing bracket] (whatever-destination) in a paragraph
```
from
```
some text with a [link reference] (some other parenthetical statement) in a paragraph

[link reference]: whatever-destination-here
```
which I imagine is part of the rationale for CommonMark disallowing that space. @ashleygwilliams do you have any thoughts on this?

**Comment by revin** [comment]
I might have answered my own question. I updated [my test gist](https://gist.github.com/revin/9cea599d873886cb51bd3127b22c537c) and see that they treat the link reference followed by a parenthetical statement such that the parenthetical statement is always the link destination, even if a link reference exists. Obviously that's not standard CommonMark, but I guess that makes the requirements less ambiguous.
