### ISSUE TITLE
Missing word after README parsing on newww

### ISSUE THREAD

**Issue by qraynaud** [npm/marky-markdown#33]
I'm managing a package on npm: https://www.npmjs.com/package/glou.

As you can see on this page, the subtitle of the package is « Complete pipelining system compatible Gulp ». My problem is that in my markdown the subtitle is « Complete pipelining system compatible with Gulp » (there is « with » in the correct sentence but not on npm).

You can check this in the repository…

**Comment by zeke** [comment]
The description is pulled from your package.json description: https://bitbucket.org/lsystems/glou/src/b59b1a0a3c5c2e2f64683b57637a72edb6ca9d14/package.json?at=default
