### ISSUE TITLE
Not getting .getParser() in downloaded npm package

### ISSUE THREAD

**Issue by fmvilas** [npm/marky-markdown#331]
Hi,

For some reason the downloaded package I get from npm is not containing the `.getParser()` function, however I can see it in the code https://github.com/npm/marky-markdown/blob/master/index.js#L49. Is it probably not published yet?

Cheers!

**Comment by revin** [comment]
You guessed it, @fmvilas; that will be in version 10. If you want `getParser()`, for now the solution is to clone marky from github here.

**Comment by fmvilas** [comment]
Cool! Thanks for the reply @revin. Remember `getParser()` is described on README, that's what got me confused.

**Comment by revin** [comment]
@fmvilas the README here on github, but not on npmjs.com, right? If it's showing up on the npm site, that's definitely an issue.

**Comment by fmvilas** [comment]
Yes, on Github. When I did a search on Google I directly came to Github and assumed `master` branch was in sync with npm package. So it's not an issue but just wanted to give you my feedback on that 😊

**Comment by revin** [comment]
ah, I gotcha. Noted, thanks!
