### ISSUE TITLE
Markdown: Add support for <details> / <summary> html5 tags

### ISSUE THREAD

**Issue by jefflembeck** [npm/marky-markdown#332]
GitHub support the HTML5 `<details>` tag, as you can see [here](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
But it seems like they are just stripped from the Markdown on npm's website

copied from: https://github.com/npm/www/issues/116

**Comment by revin** [comment]
Thanks @jefflembeck; that's a pretty simple fix, just a matter of allowing those elements through the sanitizer. Submitted a PR for it.
