### ISSUE TITLE
Dumb question - linebreaks

### ISSUE THREAD

**Issue by ORESoftware** [npm/marky-markdown#339]
With _Github flavored markdown_, it seems I can do linebreaks with

`<br>`

and it also seems I can embolden with

`<b>`

how can I do the same with Marky Mark?

Do any html tags work with MM?

**Comment by revin** [comment]
Hi @ORESoftware, thanks for asking! This _should_ be supported; if it's not working, there might be something specific to your input that's causing it to fail. Would you mind pasting your full example?

For example, I ran this through marky:
```markdown
This is a test.<br>This is another line; here's some <b>bold text</b>.
```
and got this rendered HTML:
```html
<p>This is a test.<br />This is another line; here's some <b>bold text</b>.</p>
```

Seeing your input in context would definitely help. Thanks!

**Comment by ashleygwilliams** [comment]
hey @ORESoftware! seems like @revin answered your question! if not please reply to this! 

p.s. we don't believe in dumb questions 😉 so don't hesitate to ask more here!
