### ISSUE TITLE
add option that would include a debug message in generated HTML

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#344]
came from a convo with @chrisdickinson and @bcoe 

<hr/>

if a debug option is set to true, add an HTML comment that looks something like this to the top of the generated HTML:

```html
<!-- this HTML was generated using marky-markdown version ##.##.##. see an issue? file at <issue link>. please include the version in your issue. thanks for using marky! -->
```

**Comment by revin** [comment]
Hey that's a cool idea, nice one 👍

**Comment by ashleygwilliams** [comment]
right @revin? came up because we now have a way to render some readmes on one version of marky and not on others so without this, this could be really hard to debug without this info. additionally it opens up the option to help npm users know where to file issues re their readme. we are also working on stuff with the generator to have this version info in the metadata, but seemed cool for general use marky as well :)

**Comment by revin** [comment]
@ashleygwilliams @chrisdickinson @bcoe would it be acceptable to only do this when run in node? If we don't hide this behind a check like `typeof process.browser === 'undefined'` then marky's package.json gets added to the browserify bundle, and we probably don't want that, right?

**Comment by revin** [comment]
I guess an answer like, "it won't be built in if you do _x_" would also be acceptable; my test implementation is just doing `require('./package.json')` and reading from the resulting object.

**Comment by revin** [comment]
oh hrm I spoke too soon and was misreading my output; looks like the package.json gets included in the browserify build either way.

Maybe it doesn't matter, because I mean we're just giving people the issues URL anyway; it's not like we're trying to hide anything :)

**Comment by bcoe** [comment]
@revin hey, what if we passed a configuration option into `mark` itself:

```js
marky('# hello world', {debug: true})
```
or some such thing ... wouldn't this be useful in both the browser and in Node.js?

**Comment by revin** [comment]
@bcoe that's how the options object currently works, so yes :)

My stream of consciousness comments were basically about how to get the package version and github URL out of package.json without hard coding their values in our code; if there's a better idiomatic way than just `require('./package.json')` then I'm all ears. I'm basically a n00b on server side node stuff.

**Comment by bcoe** [comment]
@revin ah yes, I hadn't thought of this annoyance. Part of me wonders if we could just bake the version variable into the module at publish time with a tiny build-step?

I could see this feature being useful on both the server and client side, and adding a minimal build-step might be better than feature detecting Node.js?

I've looked at this for doing something similar in the past:

https://github.com/sweet-js/sweet.js/wiki/Example-macros
