### ISSUE TITLE
undefined in JS code

### ISSUE THREAD

**Issue by lachrist** [npm/marky-markdown#36]
Hi, first thanks for porting markdown to npm!
It seems you do not print well 'undefined' identifier within javascript code listing (cf my project github/lachrist/aran).
Github: 
![github](https://cloud.githubusercontent.com/assets/5468597/6937946/dca8dd7e-d85f-11e4-8b12-08f9d163f207.png)
Npm:
![npm](https://cloud.githubusercontent.com/assets/5468597/6937953/e5041e3e-d85f-11e4-879d-b69d01bb8894.png)

Regards, Laurent

**Comment by zeke** [comment]
This fix will land when we ship newww's `r2` branch, which has a newer version of marky-markdown (5) with the updated `sanitize-html` dependency: https://github.com/npm/marky-markdown/releases
