### ISSUE TITLE
relative to absolut path conversion not working with repository shortcut syntax

### ISSUE THREAD

**Issue by rudolfsonjunior** [npm/marky-markdown#368]
The conversion from a relative path e.g 

`<img src="html/block.png" />` 

to an absolute path e.g.

`<img src="https://raw.githubusercontent.com/mark/wahlberg/HEAD/html/block.png">` 

is not working with a `package.json` that uses the [npm repository shortcut syntax](https://docs.npmjs.com/files/package.json#repository) 

e.g.

```json
{
  "name": "wahlberg",
  "repository": "mark/wahlberg"
}
```

it only works with

```json
{
  "name": "wahlberg",
  "repository": {
      "type": "git",
      "url": "https://github.com/mark/wahlberg"
    }
}
```

many packages out there, have links or images in their readme, that are not working or not displayed correctly on npmjs.com, but they are working on their github repository. we discussed this issue already on SamVerschueren/listr#61, because [listr](https://www.npmjs.com/package/listr) makes use of the shortcut syntax for the repository in their `package.json`.

but since `marky-markdown` is the thing that parses package READMEs on [http://www.npmjs.com](http://www.npmjs.com), it should work also with the shortcut syntax since it is in the [official docs from npm](https://docs.npmjs.com/files/package.json#repository), right?

I ran the tests from `./test/repo-github.js` with `"repository": "name/repo"`, `"repository": "github:name/repo"`, and 

```json
{
  "name": "wahlberg",
  "repository": {
      "type": "git",
      "url": "https://github.com/mark/wahlberg"
    }
}
```

and it is only working with the last one.
 
Possible solution if the shortcut syntax should be supported:

on `line 52` in `./lib/plugin/github.js` you get the url from `opts.package.repository.url` but it should also support `opts.package.repository` if `opts.package.repository.url` is `undefined`.

**Comment by revin** [comment]
Hi @rudolfsonjunior, nice catch, thanks for filing!

This definitely seems like something marky should support. We've talked a little bit about moving the package handling code to a new project (see #257), but until that's fully worked out, I guess that responsibility lies here (and would move into that new project anyway).

As always, PRs more than welcome (and celebrated!) 😄

**Comment by revin** [comment]
ok it was exactly as simple as the suggestion in the OP, so I pushed a quick PR just now
