### ISSUE TITLE
handle tabs and newlines in package descriptions

### ISSUE THREAD

**Issue by zeke** [npm/marky-markdown#37]
https://www.npmjs.com/package/clean-whitespace doesn't look right:

![screen shot 2015-04-03 at 10 40 47 pm](https://cloud.githubusercontent.com/assets/2289/6991588/87f4c7e4-da52-11e4-9839-a606e79faf6c.png)

` "description": "normalize whitepsace characters to \t \n and space",`

**Comment by passcod** [comment]
Surely that's Not A Bug. Unless you propose npm's website should break/special-case JSON escaping rules for the `description` field, this issue is really just "package author didn't escape backslashes properly".

**Comment by ashleygwilliams** [comment]
yeah i'm gonna go ahead and say that i dont think this is a bug. feel free to reopen and convince me otherwise :)
