### ISSUE TITLE
markdown within html

### ISSUE THREAD

**Issue by kentor** [npm/marky-markdown#380]
Is this not supported?

e.g.

```
<center>`some code`</center>
```

Will just show backticks instead of `<code>`

**Comment by revin** [comment]
Hi @kentor! I'm not at a computer to verify how this works on github at the moment but I know that in CommonMark, that will be considered either an HTML block or inline HTML, depending on where it appears. And inside HTML, no further markdown is processed.

Our goal is to do whatever github does, so if there's a difference between marky-markdown and github, we consider that a bug.

**Comment by kentor** [comment]
I just tested on a gist. Yeah github doesn't allow markdown in HTML, so I'll close this. Thanks!
