### ISSUE TITLE
marky-markdown can go into an infinite loop rendering

### ISSUE THREAD

**Issue by bcoe** [npm/marky-markdown#381]
we found a README in production that forces marky-markdown into an infinite rendering loop in v10:

https://gist.github.com/bcoe/d03e7002657a83ae6a475b492cf10539

we've downgraded to v9, and the file is able to be rendered; any thoughts @revin?

**Comment by bcoe** [comment]
having dug a bit more, I've narrowed things down to the `abstemiousHtmlBlocks` plugin, it seems to be called infinitely, for the `happn-primus` README .

**Comment by revin** [comment]
oof! ok thanks, I'll dig into it. I bet there's something wonky happening where that document contains a series of consecutive HTML blocks under the Community Plugins heading.

**Comment by revin** [comment]
_sigh_ well I think I figured it out; PR attached. It only has the lines of code necessary to fix this; no tests. Any ideas on the best way to test against a regression in this logic? The main symptom is just obscenely long rendering times in long enough documents with many HTML blocks.

**Comment by bcoe** [comment]
@revin nothing to _sigh_ about, thanks for digging into this -- could we create a test that runs marky on a block of code that would infinite loop, and just assert that the test does finish?

**Comment by revin** [comment]
@bcoe that sounds like the best way to do it, but I don't know enough node to know how to do that; if the infinite loop is blocking the JS event loop from ever returning control to mocha, how can we take control back? Is this a case where we should use a Worker to `eval` a script that we know will hang?

**Comment by bcoe** [comment]
@revin I would try to find the snippet of code that resulted in the infinite loop; and add a test with this code before your fix; this code should timeout in tests.

Then, with your fix in place, the test will simply start passing rather than timing out.

**Comment by revin** [comment]
@bcoe that's just it, I tried importing that whole readme into our test suite and setting up a test to parse it, but it never times out. It's all synchronous code, so I imagine it's the same issue as [this one from mocha](https://github.com/mochajs/mocha/issues/1609#issuecomment-83891411). The last comment in that thread mentions `tripwire` (which library looks like it includes a native component) to help with this sort of thing. Maybe that's the answer.

**Comment by revin** [comment]
`tripwire` seems to be doing the trick; test passes locally. Travis is verifying now.
