### ISSUE TITLE
Images with titles wrapped in parentheses are no longer rendering correctly on npmjs.com

### ISSUE THREAD

**Issue by simov** [npm/marky-markdown#384]
```markdown
[![npm-version]][npm]
![1]

  [1]: http://i.imgur.com/rKYxW.jpg (Oh Hi)
  [npm-version]: https://img.shields.io/npm/v/slack-command-hackernews.svg?style=flat-square (NPM Package Version)
  [npm]: https://www.npmjs.com/package/slack-command-hackernews
```

[![npm-version]][npm]
![1]

  [1]: http://i.imgur.com/rKYxW.jpg (Oh Hi)
  [npm-version]: https://img.shields.io/npm/v/slack-command-hackernews.svg?style=flat-square (NPM Package Version)
  [npm]: https://www.npmjs.com/package/slack-command-hackernews

I have been using this syntax since forever:

```
  [0]: url (title)
  [named]: url (title)
```

The other day I published a new module and [it doesn't work any more](https://www.npmjs.com/package/slack-command-hackernews)  
This is the [markdown](https://raw.githubusercontent.com/simov/slack-command-hackernews/master/README.md), just tested with **10.1.2** locally.

It works with quoted titles:

```
  [1]: url "title"
  [named]: url "title"
```

But I have lots of modules using the parentheses syntax already and probably I'm not alone.

**Comment by revin** [comment]
Hi @simov, thanks for reporting! This is definitely a bug with link/image parsing; we'll get it fixed.

**Comment by simov** [comment]
Thanks!

**Comment by revin** [comment]
OK, merged a PR for it, and published marky 10.1.3. Getting it live on the site will depend on how busy the npm folks are 😛

**Comment by revin** [comment]
PS: I put marky 10.1.3 in my [live marky tester](https://revin.github.io/marky-markdown/) and it renders your README as expected 🎉 🎉 🎉

**Comment by simov** [comment]
Nice! Thanks for the link :+1:

**Comment by simov** [comment]
@revin how can I know if the next release of the NPM's website is rolled out? I think the module's readme is generated on publish, so I'm not sure if it's ok to publish again.

**Comment by revin** [comment]
@bcoe would you mind pinging us here when 10.1.3 is rolled out?

**Comment by revin** [comment]
@simov ok, so two things:

1) 10.1.3 is live on the site, so you're good to go
2) To see the currently deployed version without publishing something yourself, go to the npm home page, choose something from the "recently updated packages" section, then view source on the package page, then search for "marky" and you'll see the debug comment indicating the version.

**Comment by simov** [comment]
Thanks for your support again, I appreciate it!

That's a good tip too, the funny thing was that I wasn't logged in so it took me awhile to figure out where that section was :)

:sparkles:
