### ISSUE TITLE
comments at top of markdown document can eat the entire document

### ISSUE THREAD

**Issue by bcoe** [npm/marky-markdown#388]
a document starting with:

```
<!---

my comment at the top of the .md file

--->
```

results in an empty document being rendered.

**Comment by revin** [comment]
This works for me in a short test; do you have the actual package in question handy?

**Comment by bcoe** [comment]
@revin try adding spaces before and after `my comment at the top of the .md file`.

**Comment by revin** [comment]
@bcoe tried it with 1–6 spaces of leading+trailing padding; still works locally 😕

**Comment by revin** [comment]
AH, you meant vertical spaces. Got it; replicated; will investigate!

**Comment by bcoe** [comment]
Here's an example:

```md
# react-useragent
<!--
[![Travis][build-badge]][build]
[![npm package][npm-badge]][npm]
[![Coveralls][coveralls-badge]][coveralls]

[build-badge]: https://img.shields.io/travis/quentin-sommer/react-useragent/master.png?style=flat-square
[build]: https://travis-ci.org/quentin-sommer/react-useragent

[npm-badge]: https://img.shields.io/npm/v/npm-package.png?style=flat-square
[npm]: https://www.npmjs.org/package/npm-package

[coveralls-badge]: https://img.shields.io/coveralls/quentin-sommer/react-useragent/master.png?style=flat-square
[coveralls]: https://coveralls.io/github/quentin-sommer/react-useragent
-->

Integrate user-agent detection in an idiomatic React way

## Installation

`yarn add @quentin-sommer/react-useragent` or `npm i -s @quentin-sommer/react-useragent`

## Introduction
```

**Comment by revin** [comment]
Yeah, interesting. So per CommonMark, `<!--` starts an HTML block, but then blank lines terminate it. So the rest are just paragraphs. I bet this will require a combination of markdown-it token stream work and tweaking the sanitizer.

**Comment by revin** [comment]
[markdown-it's online tester](https://markdown-it.github.io/) can handle this case, so I guess it's something in our customizations.
