### ISSUE TITLE
Handle headings without spaces after hashtags?

### ISSUE THREAD

**Issue by pdehaan** [npm/marky-markdown#39]
I've noticed this in a handful of packages on npm and it seems a bit weird and edge case-y, and confusing.

https://www.npmjs.com/package/subschema

Note how the headings aren't properly parsing because the Markdown seems to be a bit "incorrect" and missing a space after the `###` and `Install` (and `Example`):

```markdown
###Install
...
###Example You provide the schema and subschema renders it. Keeping the values, and errors in check.
```

GitHub is clever enough to parse the headings at https://github.com/jspears/subschema/blob/master/Readme.md but looks like [the excellently named] marky-markdown just ignores the sketchy Markdown. Sadly, the [Markdown spec](http://daringfireball.net/projects/markdown/syntax#header) doesn't explicitly mention that there needs to be a space after the hashes, although the examples all use it. Amazingly, it looks like the reference Markdown dingus correctly converts the headings though: http://daringfireball.net/projects/markdown/dingus. But sadly it doesn't look like the Commonmark dingus does the same: http://spec.commonmark.org/dingus/, although the Commonmark spec is a lot clearer: http://spec.commonmark.org/0.17/#atx-headers

> "The opening sequence of # characters cannot be followed directly by a non-space character."

Long story longer, should marky-markdown be handling apparently controversial edge cases like `###Install`, or just give up and display the unparsed Markdown?

**Comment by ashleygwilliams** [comment]
fixed in #82
