### ISSUE TITLE
No longer need abstemious HTML block parsing?

### ISSUE THREAD

**Issue by revin** [npm/marky-markdown#391]
The reason we have the abstemious-html-block parsing plugin is because per #317 GitHub used to allow certain markdown constructs to interrupt HTML blocks, unlike standard CommonMark, which requires a blank line in between the HTML block and any subsequent markdown content.

In tracking down and testing #388, #389, & #390, I discovered that apparently GitHub has discontinued this practice. See [this gist](https://gist.github.com/revin/1d3ffd5061bb70c09a8e243c0807e4c0/3978ea5e4d40ad8cd28200dc1acc5ffe88a02e84) confirming that the markdown content following each of the images is no longer parsed as markdown.

I think we can get rid of our plugin and use markdown-it's normal HTML block parsing logic now. Thoughts, @bcoe & @ashleygwilliams?

**Comment by bcoe** [comment]
@revin 👍 I approve of this plan; feels like it might correct a few bugs folks are seeing.
