### ISSUE TITLE
JSX language support

### ISSUE THREAD

**Issue by benwiley4000** [npm/marky-markdown#395]
As noted [here](https://github.com/facebook/prop-types/pull/78), jsx-annoted code blocks which are formatted correctly on github do not use syntax highlighting on npmjs.com.

**Comment by ljharb** [comment]
Lots of our React packages use `jsx` syntax highlighting; it'd be really great if npm supported this.

**Comment by revin** [comment]
Hi @benwiley4000 & @ljharb, excellent suggestion 👍 

I put together a preliminary PR for this, but it requires JSX support in the library we use for the syntax highlighting. I submitted a PR for _that_: https://github.com/atom/highlights/pull/55; so as soon as that's ready, we can merge the one here.

Thanks!
