### ISSUE TITLE
Typescript highlighting is missing

### ISSUE THREAD

**Issue by paulirish** [npm/marky-markdown#397]
both `typescript` and `ts` are not identified and highlighted.

For example this snippet of markdown:

    ```ts
    // The remote debugging port exposed by the launched chrome
    chrome.port: number;

    // Method kill Chrome (and cleanup the profile folder)
    chrome.kill: () => Promise<{}>;

    // The process id
    chrome.pid: number;
    ```

**Comment by revin** [comment]
hey @paulirish good find; it seems github supports this, so we definitely should as well.

**Comment by revin** [comment]
Looks like there's already an [issue](https://github.com/atom/highlights/issues/53) filed with our highlighter, so that's nice.

**Comment by bcoe** [comment]
@paulirish going to work on getting this rolled out to npm, Inc today 👍

**Comment by bcoe** [comment]
@paulirish we'll likely be releasing some new style updates over the next few days to handle some of the syntax we don't currently catch with our rendering, but TypeScript highlighting is out the door:

https://www.npmjs.com/package/@bcoe/test-typescript-jsx
