### ISSUE TITLE
underline-style headings

### ISSUE THREAD

**Issue by es128** [npm/marky-markdown#40]
Been trying to figure out why I see lines of equal signs among package descriptions, and realized this style of markdown heading is not currently supported (although it is on github).

Examples derived from the [list of chokidar dependents](https://www.npmjs.com/browse/depended/chokidar). Arguably, the impact of this issue is worse on the list pages than the actual package description pages.

https://www.npmjs.com/package/fat-watchy
https://www.npmjs.com/package/madeye
https://www.npmjs.com/package/node-server-1412
https://www.npmjs.com/package/vsd
https://www.npmjs.com/package/quiver-file-component

Maybe a separate issue, but there are also still examples like this with the redundant heading:
https://www.npmjs.com/package/vmd

**Comment by revin** [comment]
The READMEs in the linked packages render correctly now for me when using a `marky-markdown` fork I pulled down today. I haven't gone through the history of `markdown-it` to know for sure, but it looks like maybe something got fixed there, and that took care of it? Same applies to the link in #78.

**Comment by ashleygwilliams** [comment]
this appears to be solved. closing.

**Comment by es128** [comment]
Yes, the markdown parsing for underlined headings does appear to work properly on master, but there are still rendering issues with the example links I provided. Not sure whether it's just awaiting a release to production.
