### ISSUE TITLE
CLI help and version flags

### ISSUE THREAD

**Issue by SheetJSDev** [npm/marky-markdown#407]
```
$ marky-markdown -h
/usr/local/lib/node_modules/marky-markdown/bin/marky-markdown.js:14
  if (err) throw err
           ^

Error: ENOENT: no such file or directory, open '/private/tmp/-h'


```

There's a help message that only shows up with no arguments:

```
$ marky-markdown 
Usage:

marky-markdown some.md > some.html
```

I'd suggest supporting a few flags:
- `-h` or `--help` to display the help message (maybe it can be collapsed to one line like `Usage: marky-markdown some.md > some.html`)
- `-V` or `--version` to display the version number (which would be available from the bin script as `require('../marky.json').version`)

**Comment by revin** [comment]
Good ideas. I find myself wanting better CLI options all the time, personally.
