### ISSUE TITLE
Handle CommonMark-incompliant multiline HTML comments without clobbering comments in code blocks

### ISSUE THREAD

**Issue by zeke** [npm/marky-markdown#42]
`markdown-it` freaks out on [malformed/spec-incompliant](https://github.com/markdown-it/markdown-it/issues/51#issuecomment-94654680) multiline HTML comments:

- https://www.npmjs.com/package/cordova-plugin-camera
- https://www.npmjs.com/package/cordova-plugin-device
- https://www.npmjs.com/package/cordova-plugin-contacts
- https://raw.githubusercontent.com/rwaldron/johnny-five/master/README.md
- https://github.com/npm/newww/issues/867

A while back I [added some code](https://github.com/npm/marky-markdown/commit/915970757d4a1ff5eb221e83ca0b44e182e9aee4
) to marky-markdown that removed HTML comments from strings before passing them to the `markdown-it` parser. This solved the problem for the above-mentioned READMEs, but introduced new problems in other places. Some READMEs contain  HTML comments within code blocks, and those should not be removed. For example:

- https://www.npmjs.com/package/gulp-inject#basic-usage
- https://www.npmjs.com/package/essi#def

There are at least two possible solutions to this:

1. Figure out a way to remove HTML comments that aren't within a code block.
1. Write a [custom html_block function](https://github.com/markdown-it/markdown-it/issues/51#issuecomment-94654680) for `markdown-it`

**Comment by puzrin** [comment]
https://github.com/markdown-it/markdown-it/blob/master/CHANGELOG.md#440--2015-07-18

Should be fixed in `markdown-it` 4.4.0, you need to upgrade dependency.

**Comment by zeke** [comment]
:clap: Thank you @soldair and @puzrin
