### ISSUE TITLE
Phone Number Links Not Being Seen

### ISSUE THREAD

**Issue by robmuh** [npm/marky-markdown#427]
![screen shot 2018-02-20 at 8 03 44 pm](https://user-images.githubusercontent.com/3749067/36457687-4ecc2c12-1679-11e8-8801-19befd186095.png)
![screen shot 2018-02-20 at 8 03 56 pm](https://user-images.githubusercontent.com/3749067/36457690-50933798-1679-11e8-9dff-68e5e34dec2e.png)
![screen shot 2018-02-20 at 8 03 32 pm](https://user-images.githubusercontent.com/3749067/36457693-52526914-1679-11e8-9978-5ab7170c394b.png)

**Comment by robmuh** [comment]
By the way, pandoc gets this perfectly (and is just so much faster).

**Comment by revin** [comment]
@robmuh thanks for the issue! It looks like markdown-it (per the [online demo](https://markdown-it.github.io/)) renders this ok, but [github doesn't](https://gist.github.com/revin/c1f28a0309c57365f1ab4dc42f173065), at least in a gist. Do you have an example of a doc on github proper that renders this as you're expecting? If not, it would unfortunately be a non-goal of this project since the idea is to match github's output as closely as possible.

**Comment by robmuh** [comment]
GitHub has several renders internally (which I found out in a similar thread). While I find the notion of matching a flawed markdown renderer a priority, um, interesting, I actually have already found a work around (pandoc). This was just a good faith effort to let you know. Your code does not comply to any markdown spec whatsoever while it contains this bug. If you close it that is your choice and I understand the reasons even if I strongly disagree with them. Thanks for responding.

**Comment by revin** [comment]
We definitely appreciate all good faith efforts to let us know about things like this, but yes, the project's stated goal is to match GitHub's output even when it's not CommonMark (they've actually cleaned up a lot of things over time; tracking it all and matching quirks has been...interesting)—basically to be an open source JavaScript implementation of GitHub's observed renderer behavior. So this is an area where it's basically working as currently (sadly) intended 😛

**Comment by robmuh** [comment]
Do you have a link to the actual project on GitHub where I can report this? I have tried other GitHub repos and had them tell me "submit a support request"

**Comment by revin** [comment]
Oh, great question. The only one I know of is https://github.com/github/cmark/, but I'm not sure if that's the one they use in production, or is just for GFM spec purposes.
