### ISSUE TITLE
Relative links in markdown README not being rewritten on npmjs.org

### ISSUE THREAD

**Issue by JohnRGee** [npm/marky-markdown#432]
Short version: relative links to other files from my package README are not being turned into github absolute references, and so do not work on npmjs.org.

## What I Did

In my [raw README](
https://raw.githubusercontent.com/JohnRGee/nvh/master/README.md) I have relative links like:

    See [Proxy Server](docs/proxy-server.md) for variables and advice for using a proxy server.

## What I Expected

I assumed it would Just Work on both GitHub and npm, without thinking about the complications for npm hosting! (The other markdown file is not included in the published npm package.)

## What Happened Instead

On npmjs the link does not work. The [README](
https://www.npmjs.com/package/@shadowspawn/nvh) page source has the relative link and has not been rewritten, and the page is not found:

    <p>See <a href="docs/proxy-server.md" rel="nofollow">Proxy Server</a> for variables and advice for using a proxy server.</p>

On GitHub the [README](
https://github.com/JohnRGee/nvh) page source has:

    <p>See <a href="/JohnRGee/nvh/blob/master/docs/proxy-server.md">Proxy Server</a> for variables and advice for using a proxy server.</p>

## Details

When I did some digging into the problem I found that marky-markdown has support for rewriting relative links and images using the github package.repository if that is available (#306). Sounds good! But this does not appear to be happening for me.

I checked that github-url-to-object used by marky-markdown could resolve the repository as specified in my package.json and it could.

I changed my package repository reference to https in case #368 had resurfaced, but it did not make a difference.

I found another person talking about various problems with linked images, and they have a sample package with lots of types of links. None of the relative images render on npmjs:

<https://www.npmjs.com/package/@code-therapy/packages-with-readme-relative-images>

(I posted a message on the [npm community](https://npm.community/t/relative-links-in-npm-readme-markdown-not-functional/1525) but didn't score any replies in a couple of weeks.)

**Comment by JohnRGee** [comment]
I saw links working in `yargs` using a technically still relative link starting with a slash, which I had not considered.

I changed `docs/foo` to `/docs/foo`. Working on npm too now!

**Comment by JohnRGee** [comment]
Filling in some details of setups.

Working link on npmjs for yargs:
- [README](https://raw.githubusercontent.com/yargs/yargs/master/README.md): `[tons more](/docs/api.md)`
- git repo: https://github.com/yargs/yargs
- npm: https://www.npmjs.com/package/yargs

Broken link on npmjs for me:
- [README](https://raw.githubusercontent.com/JohnRGee/nvh/master/README.md): `[changes to command syntax](/docs/coming-from-n.md)`
- git repo: https://github.com/JohnRGee/nvh
- npm: https://www.npmjs.com/package/@shadowspawn/nvh

**Comment by JohnRGee** [comment]
There was a bug on npmjs end which has been addressed, hurrah! I'll update my npm community [bug](
https://npm.community/t/relative-links-in-npm-readme-markdown-not-functional/1525) when I have seen it working.

**Comment by cybairfly** [comment]
I thought this was just a bug and cannot believe this is actually the standard behavior on npm. How can relative links work anywhere else but on npm where I publish the package? Is there any official solution? It's madness!!! ;-)
