### ISSUE TITLE
Allow width/height for <img />

### ISSUE THREAD

**Issue by monolithed** [npm/marky-markdown#49]
![1430862151248](https://cloud.githubusercontent.com/assets/803674/7483603/ce19ad12-f388-11e4-8159-8799d4c5e8b1.png)
![1430862129004](https://cloud.githubusercontent.com/assets/803674/7483604/ce19e912-f388-11e4-9572-c6e39917c4c5.png)

It's really ugly

**Comment by rreusser** [comment]
PR submitted: npm/marky-markdown#50

**Comment by ashleygwilliams** [comment]
this should have been closed when https://github.com/npm/marky-markdown/pull/50 was merged. closing.
