### ISSUE TITLE
Consider switch to `markdown-it` parser

### ISSUE THREAD

**Issue by puzrin** [npm/marky-markdown#5]
In https://github.com/npm/newww/issues/487#issuecomment-68662039 @KenanY recommended to forward issue to your repo.

Consider switch to [markdown-it](https://github.com/markdown-it/markdown-it) - much more safe than current one.

**Comment by puzrin** [comment]
Please, note, that markdown-it follows latest [CommonMark](http://commonmark.org/) spec and there CAN be minor differences, if you expect output exactly like github does. For example, like [this](https://github.com/markdown-it/markdown-it/issues/26).

But at least, if you need exact GH output, change of separate rules is not very difficult.

**Comment by fengmk2** [comment]
@zeke see https://github.com/chjj/marked/issues/506

**Comment by fengmk2** [comment]
I will send a pr for this.

**Comment by zeke** [comment]
Landed in https://github.com/npm/marky-markdown/pull/15
