### ISSUE TITLE
superscript tags are stripped out

### ISSUE THREAD

**Issue by scurker** [npm/marky-markdown#55]
This is related specifically to superscript tags, but could be related to any other relative safe html tag. I ran into this in the documentation of currency.js ([Github](/scurker/currency.js) vs [npm](https://www.npmjs.com/package/currency.js)) where a superscript tag is being stripped out which leads to a fundamental difference in how the documentation is read.

**Github:**
![github](https://cloud.githubusercontent.com/assets/1062039/9804702/26c2c0d0-57f6-11e5-8927-fe1dfd8fccb5.png)

**npm:**
![npm](https://cloud.githubusercontent.com/assets/1062039/9804724/8a7fd7d4-57f6-11e5-8b04-18d4ea53adcf.png)

This seems like a relative safe tag to include, and it would be nice if npm could also match [Github's whitelist of tags](https://github.com/jch/html-pipeline/blob/2a55955b5da482624df95ff5cf88ba7ff522e97a/lib/html/pipeline/sanitization_filter.rb#L112) in order to have similar formats for readme documentations that are listed in both places.

**Comment by ashleygwilliams** [comment]
fixed by #83
