### ISSUE TITLE
Support parsing of markdown syntax for emojis

### ISSUE THREAD

**Issue by patriciarealini** [npm/marky-markdown#59]
I am working on the following issue for [npm/newww](https://github.com/npm/newww).

[<img width="780" alt="screen shot 2015-10-18 at 11 06 30 am" src="https://cloud.githubusercontent.com/assets/7608497/10564608/57f22812-7588-11e5-8bd7-ea3406e41f78.png">](https://github.com/npm/newww/issues/463)

I was thinking I would approach this issue by requiring [Markdown-It-Emoji](https://github.com/markdown-it/markdown-it-emoji) in [marky-markdown](https://github.com/npm/marky-markdown) (which already requires [Markdown-It](https://github.com/markdown-it/markdown-it)).

**Comment by ashleygwilliams** [comment]
hey! this sounds p cool. could you open a WIP PR so i can get a sense of how you would implement it? thanks for helping!

**Comment by patriciarealini** [comment]
https://github.com/npm/marky-markdown/pull/87
