### ISSUE TITLE
cut new minor version

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/marky-markdown#76]
waiting to merge #60 

- all up to date deps
- supports iojs, 4, 5
- github slugs
- fully qualified links, link
- lazy headers
- diff syntax
- emoji

this will be a fun one and maybe worth an announcement

**Comment by patriciarealini** [comment]
:tada:

**Comment by ashleygwilliams** [comment]
related #80

**Comment by ashleygwilliams** [comment]
closed by #88
