### ISSUE TITLE
headings are not parsed if they are not surrounded by whitespace

### ISSUE THREAD

**Issue by aredridel** [npm/marky-markdown#78]
From https://github.com/npm/newww/issues/1644:

> [According to the spec](http://spec.commonmark.org/0.17/#setext-headers), setext headers do not have to be followed by a blank line.

> [Example of an incorrectly rendered setext header](https://www.npmjs.com/package/react-ios-switch)

**Comment by revin** [comment]
The linked README renders correctly now for me when using a `marky-markdown` fork I pulled down today. I haven't gone through the history of `markdown-it` to know for sure, but it looks like maybe something got fixed there, and that took care of it? Same applies to the links in #40.

**Comment by ashleygwilliams** [comment]
hey @aredridel do you still see this issue if you pull marky from master? sounds like it is fixed with the new version per @revin ... lemme know!

**Comment by ashleygwilliams** [comment]
i think #82 solved this reopen if you still see this issue.
