### ISSUE TITLE
readme URLs aren't autolinked as they are on github

### ISSUE THREAD

**Issue by ljharb** [npm/marky-markdown#81]
Compare [tape readme on github](https://github.com/substack/tape/blob/5ca83621c072dc99b40335cd37cc686d48a588ea/readme.markdown#pretty-reporters) to [tape readme on npm](https://www.npmjs.com/package/tape#pretty-reporters).

Even though these URLs aren't explicit links in the markdown, Github detects that they're links and makes them clickable automatically. It would be ideal if `npmjs.com` did this as well.

As reported [here](https://github.com/substack/tape/pull/231#issuecomment-167611310) and [here](https://github.com/npm/newww/issues/1698)

**Comment by zeke** [comment]
Hi @ljharb! I've got a pending PR that addresses this: https://github.com/npm/marky-markdown/pull/79

**Comment by ljharb** [comment]
Awesome, thanks :-D

**Comment by ashleygwilliams** [comment]
fixed by #79
