### ISSUE TITLE
Restrict emoji substitution to colon-wrapped words

### ISSUE THREAD

**Issue by cloakedninjas** [npm/marky-markdown#95]
As per npm/newww#463 emoticons are being rendered into markdown which doesn't match Github's method. Emoji substitution ideally would only replace colon-wrapped items, e.g. [colon]+1[colon] -> :+1: 

Example error: https://www.npmjs.com/package/rumpus

**Comment by revin** [comment]
`markdown-it-emoji` does the colon-delimited emoji replacement, but it also has this notion of "shortcuts" where it does pattern matching to replace regular text-style smilies with unicode versions as well. PR #97 disables the shortcuts, which if I'm understanding this issue correctly, should be all we need to do.

**Comment by ashleygwilliams** [comment]
closed by #97

**Comment by ashleygwilliams** [comment]
@cloakedninjas thanks so much for this issue. this will be landing in `7.0.0` by the end of the week.

**Comment by ashleygwilliams** [comment]
actually, i'mma make this `6.0.2` since it is fixing a bug.
